### PR TITLE
Submission for: solid-gstatem

### PR DESCRIPTION
**Pull request by shuieryin**
Repository: https://github.com/gstatem/gstatem/tree/main/packages/solid-gstatem
Docs: https://gstatem.netlify.app/?path=/docs/solid-basic-usage--page

### CODE REVIEW

**Comment by orenelbaum** [comment]
validate

**Comment by shuieryin** [comment]
validate

**Comment by davedbase** [comment]
@shuieryin I noticed you are attempting to use a package in a monorepo, you'd have to add these values to the main package.json. We've been discouraging monorepos to date because it detracts from the project being a SolidHack submission.

Also the README could be used as a way to show off the project submission to sell the viewer to vote for your project. I'm sure they'll click on demo but we're encouraging users to add more useful info so it's available right on the landing page of main.

**Comment by shuieryin** [comment]
validate

**Comment by shuieryin** [comment]
validate

**Pull request merged**
