### PR TITLE
Submission for Best App: Solid E-Commerce Storefront

### PR DESCRIPTION
**Pull request by zaiste**
React.js, Next.js and Vue.js have their e-commerce storefront implementations:

* https://www.reactstorefront.io/
* https://nextjs.org/commerce
* https://www.vuestorefront.io/

**It's time for Solid.js to have one too! :)**

## Goal

This project aims to (eventually) provide a *solid* implementation of an e-commerce storefront in Solid.js using a modern stack with TypeScript, GraphQL, URQL and Tailwind CSS. Solid.js features make it an ideal solution in the e-commerce context.

**Demo:** https://solid-storefront.vercel.app
**Repository:** https://github.com/zaiste/solid-storefront

### CODE REVIEW

**Comment by orenelbaum** [comment]
validate

**Comment by orenelbaum** [comment]
@zaiste Hey, your link leads to a 404. Did you forget to make your repo public?

**Comment by zaiste** [comment]
@orenelbaum sorry about that! the repo is public now

**Comment by zaiste** [comment]
validate

**Pull request merged**
