### PR TITLE
Submission for Best Student Project Award: Bloki app 

### PR DESCRIPTION
**Pull request by MrFoxPro**
bloki-logo1

Hey. I'm glad to show my project bloki. This is editor for content creation. 
In short this is notion + miro with automatic grid layout.

Main goal is to implement simple editor that will not be restricted to one axis, but will help to place content evenly.
You can create text blocks, they will be automatically adjusted to your text size. However, initially you can create blocks only in main grid that is placed in middle of screen.
You can move it by snapping with middle mouse or by dragging icon with six dots.
In the future I'm planning to implement automatic layout, so when you will try to move block, all blocks below and grouped blocks will free space for desired place. Inline text editing, commands, nested documents, attaching drawing to text and blocks and more. I wrote a roadmap: https://github.com/MrFoxPro/bloki
 
Now there is simple demo I made for hackaton: https://bloki.app/.
There are:
- simple block types;
- grid highlighting shows whether you are allowed to place and intersections (implemented with DOM and canvas, can be chosen in settings);
- drawing with some colors and erasing;
- and all of this in real-time online mode (cursors, drawing and blocks sync);
- offline document with tutorial.
https://www.youtube.com/watch?v=PsEwt068DGk

### CODE REVIEW

**Comment by orenelbaum** [comment]
Hi, thank you for submitting your project! Can you please change your commit from:
```
### Best Student Project Award

- [Bloki app](https://github.com/MrFoxPro/bloki)
```

to:
```
### Best Student Project Award

- [Example Student Project](https://github.com/solidjs/solidhack-submissions)
- [Bloki app](https://github.com/MrFoxPro/bloki)
```

**Comment by orenelbaum** [comment]
validate

**Comment by MrFoxPro** [comment]
@orenelbaum Hello, is it ok with my submission?

**Comment by orenelbaum** [comment]
Looks like it 👍

**Pull request merged**
