### PR TITLE
Blitz: The modern state management library for Solid-JS 

### PR DESCRIPTION
**Pull request by VarunPotti**
Blitz is the modern state management library for solid, it combines the concept of svelte writables and the ease of use of recoiljs.
Here is the [website](https://blitz.dimension.dev)

### CODE REVIEW

**Comment by orenelbaum** [comment]
Hi Varun, thank you for submitting your entry to Solid hack!
Unfortunately it doesn't seem like you are following the submission rules.
First of all, your PR doesn't follow the format we provided, but more importantly, it looks like you've been working on this project for almost two years. We only accept projects that have been started after January 7th 2022. Looks like we will have to disqualify your entry. Sorry 😔

**Comment by VarunPotti** [comment]
> Hi Varun, thank you for submitting your entry to Solid hack! Unfortunately it doesn't seem like you are following the submission rules. First of all, your PR doesn't follow the format we provided, but more importantly, it looks like you've been working on this project for almost two years. We only accept projects that have been started after January 7th 2022. Looks like we will have to disqualify your entry. Sorry 😔

Hey @orenelbaum, I used the template from [solid-starter](https://github.com/amoutonbrady/solid-lib-starter) which was created 2 years ago my actual [commit](https://github.com/dimensionhq/blitz/tree/1ca44caffe4d2555f9a5452e92d5840534d50a8a) was created on the first of march

**Comment by orenelbaum** [comment]
Oh ok. So we probably won't disqualify you but we will have to see what @davedbase says.

**Comment by orenelbaum** [comment]
It will probably help if you open a new PR and follow the format for submitting PRs - https://hack.solidjs.com/submit

**Comment by VarunPotti** [comment]
> Oh ok. So we probably won't disqualify you but we will have to see what @davedbase says.

Wow, you have no idea how happy this makes me! I submitted a new [PR](https://github.com/solidjs/solidhack-submissions/pull/31), thank you so much!

**Pull request closed without merging**
